MODEL:
  BACKBONE: vit_base_patch14_dinov2
  WEIGHTS: null

DATA:
  DATASET: OCCLUSION_LINEMOD  # Options: LINEMOD, OCCLUSION_LINEMOD, YCBV
  DATA_ROOT: D:/University/Classes/CV/6dpose/OCCLUSION_LINEMOD
  OBJECT_ID: ape
  START_IDX: 1
  END_IDX: 100
  SEQ_ID: 48 # Only for YCBV (scene ID)

PATHS:
  MESH: assets/recon_meshes/ape.ply
  OUTPUT_DIR: outputs/experiment_name

RENDER:
  N_VIEWS: 400
  ELEVATION_DEG: [0, 60]
  AZIMUTH_DEG: [0, 360]
  DISTANCE: 0.7
  IMG_SIZE: [480, 640]
  FOV_DEG: 57

MATCH:
  TOPK: 2000

REFINE:
  RANSAC_ITERS: 2000
  INLIER_THRESH: 0.01

EVAL:
  ADD_THRESH: 0.1
  SYMMETRIC_OBJECTS: ['eggbox', 'glue', 'bowl', 'clamp', 'extra_large_clamp'] # Add symmetric objects here
SEED: 42
MODE: demo  # Options: demo, eval
